#ifndef ESP_NOW_MESSAGE_TYPES
#define ESP_NOW_MESSAGE_TYPES

#include <cstdint>

enum ESPNowMessageTypes : std::uint8_t
{
	UNDEFINED_MESSAGE = 0,

	// TEMP
	// COMMANDS
	// INCOMING
	FAN_SPEED_CHANGE,
	TEMP_THRESHOLD_CHANGE,
	MANUAL_FAN_CONTROL_CHANGE,
	// OUTGOING
	ACK_FAN_SPEED_CHANGED,
	ACK_TEMP_THRESHOLD_CHANGE,
	ACK_MANUAL_FAN_CONTROL_CHANGE,

	// READINGS
	// INCOMING
	TEMP_CHANGED,
	FAN_RPM_CHANGED,
	// OUTGOING
	ACK_TEMP_CHANGED,
	ACK_FAN_RPM_CHANGED,

	// LIGHT
	// INCOMING
	LED_STATE_CHANGE,
	MANUAL_LED_CONTROL_CHANGE,
	// OUTGOING
	ACK_LED_STATE_CHANGED,
	ACK_MANUAL_LED_CONTROL_CHANGED,

	// READINGS
	// INCOMING
	IS_DARK_CHANGED,
	// OUTGOING
	ACK_IS_DARK_CHANGED
};

#endif